/*
Chaos

Testing BillingAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi_chaos_client

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/qernal/openapi-chaos-go-client"
)

func Test_openapi_chaos_client_BillingAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test BillingAPIService AccountsPaymentMethodsCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var billingAccountId string

		resp, httpRes, err := apiClient.BillingAPI.AccountsPaymentMethodsCreate(context.Background(), billingAccountId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BillingAPIService AccountsPaymentMethodsList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var billingAccountId string

		resp, httpRes, err := apiClient.BillingAPI.AccountsPaymentMethodsList(context.Background(), billingAccountId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BillingAPIService BillingAccountsCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.BillingAPI.BillingAccountsCreate(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BillingAPIService BillingAccountsDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var billingAccountId string

		resp, httpRes, err := apiClient.BillingAPI.BillingAccountsDelete(context.Background(), billingAccountId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BillingAPIService BillingAccountsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var billingAccountId string

		resp, httpRes, err := apiClient.BillingAPI.BillingAccountsGet(context.Background(), billingAccountId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BillingAPIService BillingAccountsList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.BillingAPI.BillingAccountsList(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BillingAPIService BillingAccountsUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var billingAccountId string

		resp, httpRes, err := apiClient.BillingAPI.BillingAccountsUpdate(context.Background(), billingAccountId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BillingAPIService PaymentMethodsDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var billingPaymentMethodId string

		resp, httpRes, err := apiClient.BillingAPI.PaymentMethodsDelete(context.Background(), billingPaymentMethodId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BillingAPIService PaymentMethodsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var billingPaymentMethodId string

		resp, httpRes, err := apiClient.BillingAPI.PaymentMethodsGet(context.Background(), billingPaymentMethodId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test BillingAPIService PaymentMethodsUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var billingPaymentMethodId string

		resp, httpRes, err := apiClient.BillingAPI.PaymentMethodsUpdate(context.Background(), billingPaymentMethodId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
