/*
Chaos

Testing SecretsApiService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi-chaos-client

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/qernal/openapi-chaos-go-client"
)

func Test_openapi-chaos-client_SecretsApiService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SecretsApiService ProjectsSecretsCreate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string

		resp, httpRes, err := apiClient.SecretsApi.ProjectsSecretsCreate(context.Background(), projectId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SecretsApiService ProjectsSecretsDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string
		var secretName string

		resp, httpRes, err := apiClient.SecretsApi.ProjectsSecretsDelete(context.Background(), projectId, secretName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SecretsApiService ProjectsSecretsGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string
		var secretName string

		resp, httpRes, err := apiClient.SecretsApi.ProjectsSecretsGet(context.Background(), projectId, secretName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SecretsApiService ProjectsSecretsList", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string

		resp, httpRes, err := apiClient.SecretsApi.ProjectsSecretsList(context.Background(), projectId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SecretsApiService ProjectsSecretsUpdate", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var projectId string
		var secretName string

		resp, httpRes, err := apiClient.SecretsApi.ProjectsSecretsUpdate(context.Background(), projectId, secretName).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
