/*
Chaos

Central Management API - publicly exposed set of APIs for cloud resources

API version: 1.0.0
Contact: help@qernal.support
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_chaos_client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AuthTokenMeta type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthTokenMeta{}

// AuthTokenMeta API auth token meta
type AuthTokenMeta struct {
	Id string `json:"id"`
	// User
	UserId string `json:"user_id"`
	// Name of token
	Name string `json:"name"`
	ExpiryAt *string `json:"expiry_at,omitempty"`
	Date Date `json:"date"`
}

type _AuthTokenMeta AuthTokenMeta

// NewAuthTokenMeta instantiates a new AuthTokenMeta object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthTokenMeta(id string, userId string, name string, date Date) *AuthTokenMeta {
	this := AuthTokenMeta{}
	this.Id = id
	this.UserId = userId
	this.Name = name
	this.Date = date
	return &this
}

// NewAuthTokenMetaWithDefaults instantiates a new AuthTokenMeta object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthTokenMetaWithDefaults() *AuthTokenMeta {
	this := AuthTokenMeta{}
	return &this
}

// GetId returns the Id field value
func (o *AuthTokenMeta) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AuthTokenMeta) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AuthTokenMeta) SetId(v string) {
	o.Id = v
}

// GetUserId returns the UserId field value
func (o *AuthTokenMeta) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *AuthTokenMeta) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *AuthTokenMeta) SetUserId(v string) {
	o.UserId = v
}

// GetName returns the Name field value
func (o *AuthTokenMeta) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AuthTokenMeta) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AuthTokenMeta) SetName(v string) {
	o.Name = v
}

// GetExpiryAt returns the ExpiryAt field value if set, zero value otherwise.
func (o *AuthTokenMeta) GetExpiryAt() string {
	if o == nil || IsNil(o.ExpiryAt) {
		var ret string
		return ret
	}
	return *o.ExpiryAt
}

// GetExpiryAtOk returns a tuple with the ExpiryAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AuthTokenMeta) GetExpiryAtOk() (*string, bool) {
	if o == nil || IsNil(o.ExpiryAt) {
		return nil, false
	}
	return o.ExpiryAt, true
}

// HasExpiryAt returns a boolean if a field has been set.
func (o *AuthTokenMeta) HasExpiryAt() bool {
	if o != nil && !IsNil(o.ExpiryAt) {
		return true
	}

	return false
}

// SetExpiryAt gets a reference to the given string and assigns it to the ExpiryAt field.
func (o *AuthTokenMeta) SetExpiryAt(v string) {
	o.ExpiryAt = &v
}

// GetDate returns the Date field value
func (o *AuthTokenMeta) GetDate() Date {
	if o == nil {
		var ret Date
		return ret
	}

	return o.Date
}

// GetDateOk returns a tuple with the Date field value
// and a boolean to check if the value has been set.
func (o *AuthTokenMeta) GetDateOk() (*Date, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Date, true
}

// SetDate sets field value
func (o *AuthTokenMeta) SetDate(v Date) {
	o.Date = v
}

func (o AuthTokenMeta) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthTokenMeta) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["user_id"] = o.UserId
	toSerialize["name"] = o.Name
	if !IsNil(o.ExpiryAt) {
		toSerialize["expiry_at"] = o.ExpiryAt
	}
	toSerialize["date"] = o.Date
	return toSerialize, nil
}

func (o *AuthTokenMeta) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"user_id",
		"name",
		"date",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAuthTokenMeta := _AuthTokenMeta{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAuthTokenMeta)

	if err != nil {
		return err
	}

	*o = AuthTokenMeta(varAuthTokenMeta)

	return err
}

type NullableAuthTokenMeta struct {
	value *AuthTokenMeta
	isSet bool
}

func (v NullableAuthTokenMeta) Get() *AuthTokenMeta {
	return v.value
}

func (v *NullableAuthTokenMeta) Set(val *AuthTokenMeta) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthTokenMeta) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthTokenMeta) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthTokenMeta(val *AuthTokenMeta) *NullableAuthTokenMeta {
	return &NullableAuthTokenMeta{value: val, isSet: true}
}

func (v NullableAuthTokenMeta) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthTokenMeta) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


