/*
Chaos

Central Management API - publicly exposed set of APIs for cloud resources

API version: 1.0.0
Contact: help@qernal.support
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_chaos_client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SecretBodyCertificatePayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SecretBodyCertificatePayload{}

// SecretBodyCertificatePayload Encrypted TLS private key and plain certificate. Certificate expected in x509 pem format, key expected in pkcs8 or pkcs1 pem format. `type: certificate`
type SecretBodyCertificatePayload struct {
	// Public TLS certificate
	Certificate string `json:"certificate"`
	// Encrypted certificate private key
	CertificateValue string `json:"certificate_value"`
}

type _SecretBodyCertificatePayload SecretBodyCertificatePayload

// NewSecretBodyCertificatePayload instantiates a new SecretBodyCertificatePayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSecretBodyCertificatePayload(certificate string, certificateValue string) *SecretBodyCertificatePayload {
	this := SecretBodyCertificatePayload{}
	this.Certificate = certificate
	this.CertificateValue = certificateValue
	return &this
}

// NewSecretBodyCertificatePayloadWithDefaults instantiates a new SecretBodyCertificatePayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSecretBodyCertificatePayloadWithDefaults() *SecretBodyCertificatePayload {
	this := SecretBodyCertificatePayload{}
	return &this
}

// GetCertificate returns the Certificate field value
func (o *SecretBodyCertificatePayload) GetCertificate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Certificate
}

// GetCertificateOk returns a tuple with the Certificate field value
// and a boolean to check if the value has been set.
func (o *SecretBodyCertificatePayload) GetCertificateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Certificate, true
}

// SetCertificate sets field value
func (o *SecretBodyCertificatePayload) SetCertificate(v string) {
	o.Certificate = v
}

// GetCertificateValue returns the CertificateValue field value
func (o *SecretBodyCertificatePayload) GetCertificateValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CertificateValue
}

// GetCertificateValueOk returns a tuple with the CertificateValue field value
// and a boolean to check if the value has been set.
func (o *SecretBodyCertificatePayload) GetCertificateValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CertificateValue, true
}

// SetCertificateValue sets field value
func (o *SecretBodyCertificatePayload) SetCertificateValue(v string) {
	o.CertificateValue = v
}

func (o SecretBodyCertificatePayload) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SecretBodyCertificatePayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["certificate"] = o.Certificate
	toSerialize["certificate_value"] = o.CertificateValue
	return toSerialize, nil
}

func (o *SecretBodyCertificatePayload) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"certificate",
		"certificate_value",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSecretBodyCertificatePayload := _SecretBodyCertificatePayload{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSecretBodyCertificatePayload)

	if err != nil {
		return err
	}

	*o = SecretBodyCertificatePayload(varSecretBodyCertificatePayload)

	return err
}

type NullableSecretBodyCertificatePayload struct {
	value *SecretBodyCertificatePayload
	isSet bool
}

func (v NullableSecretBodyCertificatePayload) Get() *SecretBodyCertificatePayload {
	return v.value
}

func (v *NullableSecretBodyCertificatePayload) Set(val *SecretBodyCertificatePayload) {
	v.value = val
	v.isSet = true
}

func (v NullableSecretBodyCertificatePayload) IsSet() bool {
	return v.isSet
}

func (v *NullableSecretBodyCertificatePayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecretBodyCertificatePayload(val *SecretBodyCertificatePayload) *NullableSecretBodyCertificatePayload {
	return &NullableSecretBodyCertificatePayload{value: val, isSet: true}
}

func (v NullableSecretBodyCertificatePayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecretBodyCertificatePayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


