/*
Chaos

Central Management API - publicly exposed set of APIs for cloud resources

API version: 1.0.0
Contact: help@qernal.support
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_chaos_client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SecretRegistryPayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SecretRegistryPayload{}

// SecretRegistryPayload Secret metadata registry payload
type SecretRegistryPayload struct {
	// Private registry domain/location, when using the private docker hub registry sepcify `docker.io` > Without http scheme 
	Registry string `json:"registry"`
}

type _SecretRegistryPayload SecretRegistryPayload

// NewSecretRegistryPayload instantiates a new SecretRegistryPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSecretRegistryPayload(registry string) *SecretRegistryPayload {
	this := SecretRegistryPayload{}
	this.Registry = registry
	return &this
}

// NewSecretRegistryPayloadWithDefaults instantiates a new SecretRegistryPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSecretRegistryPayloadWithDefaults() *SecretRegistryPayload {
	this := SecretRegistryPayload{}
	return &this
}

// GetRegistry returns the Registry field value
func (o *SecretRegistryPayload) GetRegistry() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Registry
}

// GetRegistryOk returns a tuple with the Registry field value
// and a boolean to check if the value has been set.
func (o *SecretRegistryPayload) GetRegistryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Registry, true
}

// SetRegistry sets field value
func (o *SecretRegistryPayload) SetRegistry(v string) {
	o.Registry = v
}

func (o SecretRegistryPayload) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SecretRegistryPayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["registry"] = o.Registry
	return toSerialize, nil
}

func (o *SecretRegistryPayload) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"registry",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSecretRegistryPayload := _SecretRegistryPayload{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSecretRegistryPayload)

	if err != nil {
		return err
	}

	*o = SecretRegistryPayload(varSecretRegistryPayload)

	return err
}

type NullableSecretRegistryPayload struct {
	value *SecretRegistryPayload
	isSet bool
}

func (v NullableSecretRegistryPayload) Get() *SecretRegistryPayload {
	return v.value
}

func (v *NullableSecretRegistryPayload) Set(val *SecretRegistryPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableSecretRegistryPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableSecretRegistryPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecretRegistryPayload(val *SecretRegistryPayload) *NullableSecretRegistryPayload {
	return &NullableSecretRegistryPayload{value: val, isSet: true}
}

func (v NullableSecretRegistryPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecretRegistryPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


