/*
Chaos

Central Management API - publicly exposed set of APIs for cloud resources

API version: 1.0.0
Contact: help@qernal.support
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_chaos_client

import (
	"encoding/json"
)

// checks if the MetricResourceAggregationResources type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MetricResourceAggregationResources{}

// MetricResourceAggregationResources Resource(s) aggregation
type MetricResourceAggregationResources struct {
	// Array of unqiue resources
	Buckets []MetricResourceAggregationResourcesBucketsInner `json:"buckets,omitempty"`
	// Upper bound of error in document count
	DocCountErrorUpperBound *int32 `json:"doc_count_error_upper_bound,omitempty"`
	// Sum of other document counts
	SumOtherDocCount *int32 `json:"sum_other_doc_count,omitempty"`
}

// NewMetricResourceAggregationResources instantiates a new MetricResourceAggregationResources object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMetricResourceAggregationResources() *MetricResourceAggregationResources {
	this := MetricResourceAggregationResources{}
	return &this
}

// NewMetricResourceAggregationResourcesWithDefaults instantiates a new MetricResourceAggregationResources object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMetricResourceAggregationResourcesWithDefaults() *MetricResourceAggregationResources {
	this := MetricResourceAggregationResources{}
	return &this
}

// GetBuckets returns the Buckets field value if set, zero value otherwise.
func (o *MetricResourceAggregationResources) GetBuckets() []MetricResourceAggregationResourcesBucketsInner {
	if o == nil || IsNil(o.Buckets) {
		var ret []MetricResourceAggregationResourcesBucketsInner
		return ret
	}
	return o.Buckets
}

// GetBucketsOk returns a tuple with the Buckets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricResourceAggregationResources) GetBucketsOk() ([]MetricResourceAggregationResourcesBucketsInner, bool) {
	if o == nil || IsNil(o.Buckets) {
		return nil, false
	}
	return o.Buckets, true
}

// HasBuckets returns a boolean if a field has been set.
func (o *MetricResourceAggregationResources) HasBuckets() bool {
	if o != nil && !IsNil(o.Buckets) {
		return true
	}

	return false
}

// SetBuckets gets a reference to the given []MetricResourceAggregationResourcesBucketsInner and assigns it to the Buckets field.
func (o *MetricResourceAggregationResources) SetBuckets(v []MetricResourceAggregationResourcesBucketsInner) {
	o.Buckets = v
}

// GetDocCountErrorUpperBound returns the DocCountErrorUpperBound field value if set, zero value otherwise.
func (o *MetricResourceAggregationResources) GetDocCountErrorUpperBound() int32 {
	if o == nil || IsNil(o.DocCountErrorUpperBound) {
		var ret int32
		return ret
	}
	return *o.DocCountErrorUpperBound
}

// GetDocCountErrorUpperBoundOk returns a tuple with the DocCountErrorUpperBound field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricResourceAggregationResources) GetDocCountErrorUpperBoundOk() (*int32, bool) {
	if o == nil || IsNil(o.DocCountErrorUpperBound) {
		return nil, false
	}
	return o.DocCountErrorUpperBound, true
}

// HasDocCountErrorUpperBound returns a boolean if a field has been set.
func (o *MetricResourceAggregationResources) HasDocCountErrorUpperBound() bool {
	if o != nil && !IsNil(o.DocCountErrorUpperBound) {
		return true
	}

	return false
}

// SetDocCountErrorUpperBound gets a reference to the given int32 and assigns it to the DocCountErrorUpperBound field.
func (o *MetricResourceAggregationResources) SetDocCountErrorUpperBound(v int32) {
	o.DocCountErrorUpperBound = &v
}

// GetSumOtherDocCount returns the SumOtherDocCount field value if set, zero value otherwise.
func (o *MetricResourceAggregationResources) GetSumOtherDocCount() int32 {
	if o == nil || IsNil(o.SumOtherDocCount) {
		var ret int32
		return ret
	}
	return *o.SumOtherDocCount
}

// GetSumOtherDocCountOk returns a tuple with the SumOtherDocCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricResourceAggregationResources) GetSumOtherDocCountOk() (*int32, bool) {
	if o == nil || IsNil(o.SumOtherDocCount) {
		return nil, false
	}
	return o.SumOtherDocCount, true
}

// HasSumOtherDocCount returns a boolean if a field has been set.
func (o *MetricResourceAggregationResources) HasSumOtherDocCount() bool {
	if o != nil && !IsNil(o.SumOtherDocCount) {
		return true
	}

	return false
}

// SetSumOtherDocCount gets a reference to the given int32 and assigns it to the SumOtherDocCount field.
func (o *MetricResourceAggregationResources) SetSumOtherDocCount(v int32) {
	o.SumOtherDocCount = &v
}

func (o MetricResourceAggregationResources) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MetricResourceAggregationResources) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Buckets) {
		toSerialize["buckets"] = o.Buckets
	}
	if !IsNil(o.DocCountErrorUpperBound) {
		toSerialize["doc_count_error_upper_bound"] = o.DocCountErrorUpperBound
	}
	if !IsNil(o.SumOtherDocCount) {
		toSerialize["sum_other_doc_count"] = o.SumOtherDocCount
	}
	return toSerialize, nil
}

type NullableMetricResourceAggregationResources struct {
	value *MetricResourceAggregationResources
	isSet bool
}

func (v NullableMetricResourceAggregationResources) Get() *MetricResourceAggregationResources {
	return v.value
}

func (v *NullableMetricResourceAggregationResources) Set(val *MetricResourceAggregationResources) {
	v.value = val
	v.isSet = true
}

func (v NullableMetricResourceAggregationResources) IsSet() bool {
	return v.isSet
}

func (v *NullableMetricResourceAggregationResources) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMetricResourceAggregationResources(val *MetricResourceAggregationResources) *NullableMetricResourceAggregationResources {
	return &NullableMetricResourceAggregationResources{value: val, isSet: true}
}

func (v NullableMetricResourceAggregationResources) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMetricResourceAggregationResources) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


