/*
Chaos

Central Management API - publicly exposed set of APIs for managing deployments

API version: 1.0.0
Contact: support@qernal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_chaos_client

import (
	"encoding/json"
)

// checks if the PaginationLinks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PaginationLinks{}

// PaginationLinks Links object for pagination use
type PaginationLinks struct {
	Prev string `json:"prev"`
	Next string `json:"next"`
}

// NewPaginationLinks instantiates a new PaginationLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPaginationLinks(prev string, next string) *PaginationLinks {
	this := PaginationLinks{}
	this.Prev = prev
	this.Next = next
	return &this
}

// NewPaginationLinksWithDefaults instantiates a new PaginationLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPaginationLinksWithDefaults() *PaginationLinks {
	this := PaginationLinks{}
	return &this
}

// GetPrev returns the Prev field value
func (o *PaginationLinks) GetPrev() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Prev
}

// GetPrevOk returns a tuple with the Prev field value
// and a boolean to check if the value has been set.
func (o *PaginationLinks) GetPrevOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Prev, true
}

// SetPrev sets field value
func (o *PaginationLinks) SetPrev(v string) {
	o.Prev = v
}

// GetNext returns the Next field value
func (o *PaginationLinks) GetNext() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Next
}

// GetNextOk returns a tuple with the Next field value
// and a boolean to check if the value has been set.
func (o *PaginationLinks) GetNextOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Next, true
}

// SetNext sets field value
func (o *PaginationLinks) SetNext(v string) {
	o.Next = v
}

func (o PaginationLinks) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PaginationLinks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["prev"] = o.Prev
	toSerialize["next"] = o.Next
	return toSerialize, nil
}

type NullablePaginationLinks struct {
	value *PaginationLinks
	isSet bool
}

func (v NullablePaginationLinks) Get() *PaginationLinks {
	return v.value
}

func (v *NullablePaginationLinks) Set(val *PaginationLinks) {
	v.value = val
	v.isSet = true
}

func (v NullablePaginationLinks) IsSet() bool {
	return v.isSet
}

func (v *NullablePaginationLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePaginationLinks(val *PaginationLinks) *NullablePaginationLinks {
	return &NullablePaginationLinks{value: val, isSet: true}
}

func (v NullablePaginationLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePaginationLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


