/*
Chaos

Central Management API - publicly exposed set of APIs for managing deployments

API version: 1.0.0
Contact: support@qernal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi-chaos-client

import (
	"encoding/json"
)

// checks if the ListSecretResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListSecretResponse{}

// ListSecretResponse List of secrets
type ListSecretResponse struct {
	Meta PaginationMeta `json:"meta"`
	Data []SecretMetaResponse `json:"data"`
}

// NewListSecretResponse instantiates a new ListSecretResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListSecretResponse(meta PaginationMeta, data []SecretMetaResponse) *ListSecretResponse {
	this := ListSecretResponse{}
	this.Meta = meta
	this.Data = data
	return &this
}

// NewListSecretResponseWithDefaults instantiates a new ListSecretResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListSecretResponseWithDefaults() *ListSecretResponse {
	this := ListSecretResponse{}
	return &this
}

// GetMeta returns the Meta field value
func (o *ListSecretResponse) GetMeta() PaginationMeta {
	if o == nil {
		var ret PaginationMeta
		return ret
	}

	return o.Meta
}

// GetMetaOk returns a tuple with the Meta field value
// and a boolean to check if the value has been set.
func (o *ListSecretResponse) GetMetaOk() (*PaginationMeta, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Meta, true
}

// SetMeta sets field value
func (o *ListSecretResponse) SetMeta(v PaginationMeta) {
	o.Meta = v
}

// GetData returns the Data field value
func (o *ListSecretResponse) GetData() []SecretMetaResponse {
	if o == nil {
		var ret []SecretMetaResponse
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *ListSecretResponse) GetDataOk() ([]SecretMetaResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Data, true
}

// SetData sets field value
func (o *ListSecretResponse) SetData(v []SecretMetaResponse) {
	o.Data = v
}

func (o ListSecretResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListSecretResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["meta"] = o.Meta
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

type NullableListSecretResponse struct {
	value *ListSecretResponse
	isSet bool
}

func (v NullableListSecretResponse) Get() *ListSecretResponse {
	return v.value
}

func (v *NullableListSecretResponse) Set(val *ListSecretResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListSecretResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListSecretResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListSecretResponse(val *ListSecretResponse) *NullableListSecretResponse {
	return &NullableListSecretResponse{value: val, isSet: true}
}

func (v NullableListSecretResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListSecretResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


