/*
Chaos

Central Management API - publicly exposed set of APIs for cloud resources

API version: 1.0.0
Contact: help@qernal.support
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_chaos_client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DeletedResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DeletedResponse{}

// DeletedResponse Deleted Response
type DeletedResponse struct {
	Message string `json:"message"`
}

type _DeletedResponse DeletedResponse

// NewDeletedResponse instantiates a new DeletedResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDeletedResponse(message string) *DeletedResponse {
	this := DeletedResponse{}
	this.Message = message
	return &this
}

// NewDeletedResponseWithDefaults instantiates a new DeletedResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDeletedResponseWithDefaults() *DeletedResponse {
	this := DeletedResponse{}
	return &this
}

// GetMessage returns the Message field value
func (o *DeletedResponse) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *DeletedResponse) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *DeletedResponse) SetMessage(v string) {
	o.Message = v
}

func (o DeletedResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DeletedResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["message"] = o.Message
	return toSerialize, nil
}

func (o *DeletedResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"message",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDeletedResponse := _DeletedResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDeletedResponse)

	if err != nil {
		return err
	}

	*o = DeletedResponse(varDeletedResponse)

	return err
}

type NullableDeletedResponse struct {
	value *DeletedResponse
	isSet bool
}

func (v NullableDeletedResponse) Get() *DeletedResponse {
	return v.value
}

func (v *NullableDeletedResponse) Set(val *DeletedResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDeletedResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDeletedResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDeletedResponse(val *DeletedResponse) *NullableDeletedResponse {
	return &NullableDeletedResponse{value: val, isSet: true}
}

func (v NullableDeletedResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDeletedResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


