/*
Chaos

Central Management API - publicly exposed set of APIs for cloud resources

API version: 1.0.0
Contact: help@qernal.support
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_chaos_client

import (
	"encoding/json"
	"gopkg.in/validator.v2"
	"fmt"
)

// SecretMetaPayload - struct for SecretMetaPayload
type SecretMetaPayload struct {
	SecretMetaCertificatePayload *SecretMetaCertificatePayload
	SecretMetaDek *SecretMetaDek
	SecretMetaRegistryPayload *SecretMetaRegistryPayload
}

// SecretMetaCertificatePayloadAsSecretMetaPayload is a convenience function that returns SecretMetaCertificatePayload wrapped in SecretMetaPayload
func SecretMetaCertificatePayloadAsSecretMetaPayload(v *SecretMetaCertificatePayload) SecretMetaPayload {
	return SecretMetaPayload{
		SecretMetaCertificatePayload: v,
	}
}

// SecretMetaDekAsSecretMetaPayload is a convenience function that returns SecretMetaDek wrapped in SecretMetaPayload
func SecretMetaDekAsSecretMetaPayload(v *SecretMetaDek) SecretMetaPayload {
	return SecretMetaPayload{
		SecretMetaDek: v,
	}
}

// SecretMetaRegistryPayloadAsSecretMetaPayload is a convenience function that returns SecretMetaRegistryPayload wrapped in SecretMetaPayload
func SecretMetaRegistryPayloadAsSecretMetaPayload(v *SecretMetaRegistryPayload) SecretMetaPayload {
	return SecretMetaPayload{
		SecretMetaRegistryPayload: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *SecretMetaPayload) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into SecretMetaCertificatePayload
	err = newStrictDecoder(data).Decode(&dst.SecretMetaCertificatePayload)
	if err == nil {
		jsonSecretMetaCertificatePayload, _ := json.Marshal(dst.SecretMetaCertificatePayload)
		if string(jsonSecretMetaCertificatePayload) == "{}" { // empty struct
			dst.SecretMetaCertificatePayload = nil
		} else {
			if err = validator.Validate(dst.SecretMetaCertificatePayload); err != nil {
				dst.SecretMetaCertificatePayload = nil
			} else {
				match++
			}
		}
	} else {
		dst.SecretMetaCertificatePayload = nil
	}

	// try to unmarshal data into SecretMetaDek
	err = newStrictDecoder(data).Decode(&dst.SecretMetaDek)
	if err == nil {
		jsonSecretMetaDek, _ := json.Marshal(dst.SecretMetaDek)
		if string(jsonSecretMetaDek) == "{}" { // empty struct
			dst.SecretMetaDek = nil
		} else {
			if err = validator.Validate(dst.SecretMetaDek); err != nil {
				dst.SecretMetaDek = nil
			} else {
				match++
			}
		}
	} else {
		dst.SecretMetaDek = nil
	}

	// try to unmarshal data into SecretMetaRegistryPayload
	err = newStrictDecoder(data).Decode(&dst.SecretMetaRegistryPayload)
	if err == nil {
		jsonSecretMetaRegistryPayload, _ := json.Marshal(dst.SecretMetaRegistryPayload)
		if string(jsonSecretMetaRegistryPayload) == "{}" { // empty struct
			dst.SecretMetaRegistryPayload = nil
		} else {
			if err = validator.Validate(dst.SecretMetaRegistryPayload); err != nil {
				dst.SecretMetaRegistryPayload = nil
			} else {
				match++
			}
		}
	} else {
		dst.SecretMetaRegistryPayload = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.SecretMetaCertificatePayload = nil
		dst.SecretMetaDek = nil
		dst.SecretMetaRegistryPayload = nil

		return fmt.Errorf("data matches more than one schema in oneOf(SecretMetaPayload)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(SecretMetaPayload)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src SecretMetaPayload) MarshalJSON() ([]byte, error) {
	if src.SecretMetaCertificatePayload != nil {
		return json.Marshal(&src.SecretMetaCertificatePayload)
	}

	if src.SecretMetaDek != nil {
		return json.Marshal(&src.SecretMetaDek)
	}

	if src.SecretMetaRegistryPayload != nil {
		return json.Marshal(&src.SecretMetaRegistryPayload)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *SecretMetaPayload) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.SecretMetaCertificatePayload != nil {
		return obj.SecretMetaCertificatePayload
	}

	if obj.SecretMetaDek != nil {
		return obj.SecretMetaDek
	}

	if obj.SecretMetaRegistryPayload != nil {
		return obj.SecretMetaRegistryPayload
	}

	// all schemas are nil
	return nil
}

type NullableSecretMetaPayload struct {
	value *SecretMetaPayload
	isSet bool
}

func (v NullableSecretMetaPayload) Get() *SecretMetaPayload {
	return v.value
}

func (v *NullableSecretMetaPayload) Set(val *SecretMetaPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableSecretMetaPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableSecretMetaPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecretMetaPayload(val *SecretMetaPayload) *NullableSecretMetaPayload {
	return &NullableSecretMetaPayload{value: val, isSet: true}
}

func (v NullableSecretMetaPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecretMetaPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


