/*
Chaos

Central Management API - publicly exposed set of APIs for cloud resources

API version: 1.0.0
Contact: help@qernal.support
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_chaos_client

import (
	"encoding/json"
	"gopkg.in/validator.v2"
	"fmt"
)

// SecretPayload - struct for SecretPayload
type SecretPayload struct {
	SecretCertificatePayload *SecretCertificatePayload
	SecretDekPayload *SecretDekPayload
	SecretRegistryPayload *SecretRegistryPayload
}

// SecretCertificatePayloadAsSecretPayload is a convenience function that returns SecretCertificatePayload wrapped in SecretPayload
func SecretCertificatePayloadAsSecretPayload(v *SecretCertificatePayload) SecretPayload {
	return SecretPayload{
		SecretCertificatePayload: v,
	}
}

// SecretDekPayloadAsSecretPayload is a convenience function that returns SecretDekPayload wrapped in SecretPayload
func SecretDekPayloadAsSecretPayload(v *SecretDekPayload) SecretPayload {
	return SecretPayload{
		SecretDekPayload: v,
	}
}

// SecretRegistryPayloadAsSecretPayload is a convenience function that returns SecretRegistryPayload wrapped in SecretPayload
func SecretRegistryPayloadAsSecretPayload(v *SecretRegistryPayload) SecretPayload {
	return SecretPayload{
		SecretRegistryPayload: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *SecretPayload) UnmarshalJSON(data []byte) error {
	var err error
	// this object is nullable so check if the payload is null or empty string
	if string(data) == "" || string(data) == "{}" {
		return nil
	}

	match := 0
	// try to unmarshal data into SecretCertificatePayload
	err = newStrictDecoder(data).Decode(&dst.SecretCertificatePayload)
	if err == nil {
		jsonSecretCertificatePayload, _ := json.Marshal(dst.SecretCertificatePayload)
		if string(jsonSecretCertificatePayload) == "{}" { // empty struct
			dst.SecretCertificatePayload = nil
		} else {
			if err = validator.Validate(dst.SecretCertificatePayload); err != nil {
				dst.SecretCertificatePayload = nil
			} else {
				match++
			}
		}
	} else {
		dst.SecretCertificatePayload = nil
	}

	// try to unmarshal data into SecretDekPayload
	err = newStrictDecoder(data).Decode(&dst.SecretDekPayload)
	if err == nil {
		jsonSecretDekPayload, _ := json.Marshal(dst.SecretDekPayload)
		if string(jsonSecretDekPayload) == "{}" { // empty struct
			dst.SecretDekPayload = nil
		} else {
			if err = validator.Validate(dst.SecretDekPayload); err != nil {
				dst.SecretDekPayload = nil
			} else {
				match++
			}
		}
	} else {
		dst.SecretDekPayload = nil
	}

	// try to unmarshal data into SecretRegistryPayload
	err = newStrictDecoder(data).Decode(&dst.SecretRegistryPayload)
	if err == nil {
		jsonSecretRegistryPayload, _ := json.Marshal(dst.SecretRegistryPayload)
		if string(jsonSecretRegistryPayload) == "{}" { // empty struct
			dst.SecretRegistryPayload = nil
		} else {
			if err = validator.Validate(dst.SecretRegistryPayload); err != nil {
				dst.SecretRegistryPayload = nil
			} else {
				match++
			}
		}
	} else {
		dst.SecretRegistryPayload = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.SecretCertificatePayload = nil
		dst.SecretDekPayload = nil
		dst.SecretRegistryPayload = nil

		return fmt.Errorf("data matches more than one schema in oneOf(SecretPayload)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(SecretPayload)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src SecretPayload) MarshalJSON() ([]byte, error) {
	if src.SecretCertificatePayload != nil {
		return json.Marshal(&src.SecretCertificatePayload)
	}

	if src.SecretDekPayload != nil {
		return json.Marshal(&src.SecretDekPayload)
	}

	if src.SecretRegistryPayload != nil {
		return json.Marshal(&src.SecretRegistryPayload)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *SecretPayload) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.SecretCertificatePayload != nil {
		return obj.SecretCertificatePayload
	}

	if obj.SecretDekPayload != nil {
		return obj.SecretDekPayload
	}

	if obj.SecretRegistryPayload != nil {
		return obj.SecretRegistryPayload
	}

	// all schemas are nil
	return nil
}

type NullableSecretPayload struct {
	value *SecretPayload
	isSet bool
}

func (v NullableSecretPayload) Get() *SecretPayload {
	return v.value
}

func (v *NullableSecretPayload) Set(val *SecretPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableSecretPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableSecretPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecretPayload(val *SecretPayload) *NullableSecretPayload {
	return &NullableSecretPayload{value: val, isSet: true}
}

func (v NullableSecretPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecretPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


