/*
Chaos

Central Management API - publicly exposed set of APIs for cloud resources

API version: 1.0.0
Contact: help@qernal.support
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_chaos_client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SecretMetaRegistryPayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SecretMetaRegistryPayload{}

// SecretMetaRegistryPayload Secret metadata registry payload
type SecretMetaRegistryPayload struct {
	// Private registry domain/location, when using the private docker hub registry sepcify `docker.io` > Without http scheme 
	Registry string `json:"registry"`
}

type _SecretMetaRegistryPayload SecretMetaRegistryPayload

// NewSecretMetaRegistryPayload instantiates a new SecretMetaRegistryPayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSecretMetaRegistryPayload(registry string) *SecretMetaRegistryPayload {
	this := SecretMetaRegistryPayload{}
	this.Registry = registry
	return &this
}

// NewSecretMetaRegistryPayloadWithDefaults instantiates a new SecretMetaRegistryPayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSecretMetaRegistryPayloadWithDefaults() *SecretMetaRegistryPayload {
	this := SecretMetaRegistryPayload{}
	return &this
}

// GetRegistry returns the Registry field value
func (o *SecretMetaRegistryPayload) GetRegistry() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Registry
}

// GetRegistryOk returns a tuple with the Registry field value
// and a boolean to check if the value has been set.
func (o *SecretMetaRegistryPayload) GetRegistryOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Registry, true
}

// SetRegistry sets field value
func (o *SecretMetaRegistryPayload) SetRegistry(v string) {
	o.Registry = v
}

func (o SecretMetaRegistryPayload) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SecretMetaRegistryPayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["registry"] = o.Registry
	return toSerialize, nil
}

func (o *SecretMetaRegistryPayload) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"registry",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSecretMetaRegistryPayload := _SecretMetaRegistryPayload{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSecretMetaRegistryPayload)

	if err != nil {
		return err
	}

	*o = SecretMetaRegistryPayload(varSecretMetaRegistryPayload)

	return err
}

type NullableSecretMetaRegistryPayload struct {
	value *SecretMetaRegistryPayload
	isSet bool
}

func (v NullableSecretMetaRegistryPayload) Get() *SecretMetaRegistryPayload {
	return v.value
}

func (v *NullableSecretMetaRegistryPayload) Set(val *SecretMetaRegistryPayload) {
	v.value = val
	v.isSet = true
}

func (v NullableSecretMetaRegistryPayload) IsSet() bool {
	return v.isSet
}

func (v *NullableSecretMetaRegistryPayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecretMetaRegistryPayload(val *SecretMetaRegistryPayload) *NullableSecretMetaRegistryPayload {
	return &NullableSecretMetaRegistryPayload{value: val, isSet: true}
}

func (v NullableSecretMetaRegistryPayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecretMetaRegistryPayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


