/*
Chaos

Central Management API - publicly exposed set of APIs for cloud resources

API version: 1.0.0
Contact: help@qernal.support
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_chaos_client

import (
	"encoding/json"
)

// checks if the MetricResourceAggregationResourcesBucketsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MetricResourceAggregationResourcesBucketsInner{}

// MetricResourceAggregationResourcesBucketsInner Histogram bucket
type MetricResourceAggregationResourcesBucketsInner struct {
	// Number of documents in the bucket
	DocCount *int32 `json:"doc_count,omitempty"`
	Histogram *MetricResourceAggregationResourcesBucketsInnerHistogram `json:"histogram,omitempty"`
	// Metric key
	Key *string `json:"key,omitempty"`
}

// NewMetricResourceAggregationResourcesBucketsInner instantiates a new MetricResourceAggregationResourcesBucketsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMetricResourceAggregationResourcesBucketsInner() *MetricResourceAggregationResourcesBucketsInner {
	this := MetricResourceAggregationResourcesBucketsInner{}
	return &this
}

// NewMetricResourceAggregationResourcesBucketsInnerWithDefaults instantiates a new MetricResourceAggregationResourcesBucketsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMetricResourceAggregationResourcesBucketsInnerWithDefaults() *MetricResourceAggregationResourcesBucketsInner {
	this := MetricResourceAggregationResourcesBucketsInner{}
	return &this
}

// GetDocCount returns the DocCount field value if set, zero value otherwise.
func (o *MetricResourceAggregationResourcesBucketsInner) GetDocCount() int32 {
	if o == nil || IsNil(o.DocCount) {
		var ret int32
		return ret
	}
	return *o.DocCount
}

// GetDocCountOk returns a tuple with the DocCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricResourceAggregationResourcesBucketsInner) GetDocCountOk() (*int32, bool) {
	if o == nil || IsNil(o.DocCount) {
		return nil, false
	}
	return o.DocCount, true
}

// HasDocCount returns a boolean if a field has been set.
func (o *MetricResourceAggregationResourcesBucketsInner) HasDocCount() bool {
	if o != nil && !IsNil(o.DocCount) {
		return true
	}

	return false
}

// SetDocCount gets a reference to the given int32 and assigns it to the DocCount field.
func (o *MetricResourceAggregationResourcesBucketsInner) SetDocCount(v int32) {
	o.DocCount = &v
}

// GetHistogram returns the Histogram field value if set, zero value otherwise.
func (o *MetricResourceAggregationResourcesBucketsInner) GetHistogram() MetricResourceAggregationResourcesBucketsInnerHistogram {
	if o == nil || IsNil(o.Histogram) {
		var ret MetricResourceAggregationResourcesBucketsInnerHistogram
		return ret
	}
	return *o.Histogram
}

// GetHistogramOk returns a tuple with the Histogram field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricResourceAggregationResourcesBucketsInner) GetHistogramOk() (*MetricResourceAggregationResourcesBucketsInnerHistogram, bool) {
	if o == nil || IsNil(o.Histogram) {
		return nil, false
	}
	return o.Histogram, true
}

// HasHistogram returns a boolean if a field has been set.
func (o *MetricResourceAggregationResourcesBucketsInner) HasHistogram() bool {
	if o != nil && !IsNil(o.Histogram) {
		return true
	}

	return false
}

// SetHistogram gets a reference to the given MetricResourceAggregationResourcesBucketsInnerHistogram and assigns it to the Histogram field.
func (o *MetricResourceAggregationResourcesBucketsInner) SetHistogram(v MetricResourceAggregationResourcesBucketsInnerHistogram) {
	o.Histogram = &v
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *MetricResourceAggregationResourcesBucketsInner) GetKey() string {
	if o == nil || IsNil(o.Key) {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricResourceAggregationResourcesBucketsInner) GetKeyOk() (*string, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *MetricResourceAggregationResourcesBucketsInner) HasKey() bool {
	if o != nil && !IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *MetricResourceAggregationResourcesBucketsInner) SetKey(v string) {
	o.Key = &v
}

func (o MetricResourceAggregationResourcesBucketsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MetricResourceAggregationResourcesBucketsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DocCount) {
		toSerialize["doc_count"] = o.DocCount
	}
	if !IsNil(o.Histogram) {
		toSerialize["histogram"] = o.Histogram
	}
	if !IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	return toSerialize, nil
}

type NullableMetricResourceAggregationResourcesBucketsInner struct {
	value *MetricResourceAggregationResourcesBucketsInner
	isSet bool
}

func (v NullableMetricResourceAggregationResourcesBucketsInner) Get() *MetricResourceAggregationResourcesBucketsInner {
	return v.value
}

func (v *NullableMetricResourceAggregationResourcesBucketsInner) Set(val *MetricResourceAggregationResourcesBucketsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableMetricResourceAggregationResourcesBucketsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableMetricResourceAggregationResourcesBucketsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMetricResourceAggregationResourcesBucketsInner(val *MetricResourceAggregationResourcesBucketsInner) *NullableMetricResourceAggregationResourcesBucketsInner {
	return &NullableMetricResourceAggregationResourcesBucketsInner{value: val, isSet: true}
}

func (v NullableMetricResourceAggregationResourcesBucketsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMetricResourceAggregationResourcesBucketsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


