/*
Chaos

Central Management API - publicly exposed set of APIs for managing deployments

API version: 1.0.0
Contact: support@qernal.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_chaos_client

import (
	"encoding/json"
)

// checks if the MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInner{}

// MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInner struct for MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInner
type MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInner struct {
	// Number of documents in the bucket
	DocCount *int32 `json:"doc_count,omitempty"`
	Counter *MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInnerCounter `json:"counter,omitempty"`
	Gauge *MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInnerGauge `json:"gauge,omitempty"`
	// Histogram key (typically unix timestamp)
	Key *int64 `json:"key,omitempty"`
	// Histogram key as string/date-time
	KeyAsString *string `json:"key_as_string,omitempty"`
}

// NewMetricResourceAggregationResourcesBucketsInnerHistogramBucketsInner instantiates a new MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMetricResourceAggregationResourcesBucketsInnerHistogramBucketsInner() *MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInner {
	this := MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInner{}
	return &this
}

// NewMetricResourceAggregationResourcesBucketsInnerHistogramBucketsInnerWithDefaults instantiates a new MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMetricResourceAggregationResourcesBucketsInnerHistogramBucketsInnerWithDefaults() *MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInner {
	this := MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInner{}
	return &this
}

// GetDocCount returns the DocCount field value if set, zero value otherwise.
func (o *MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInner) GetDocCount() int32 {
	if o == nil || IsNil(o.DocCount) {
		var ret int32
		return ret
	}
	return *o.DocCount
}

// GetDocCountOk returns a tuple with the DocCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInner) GetDocCountOk() (*int32, bool) {
	if o == nil || IsNil(o.DocCount) {
		return nil, false
	}
	return o.DocCount, true
}

// HasDocCount returns a boolean if a field has been set.
func (o *MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInner) HasDocCount() bool {
	if o != nil && !IsNil(o.DocCount) {
		return true
	}

	return false
}

// SetDocCount gets a reference to the given int32 and assigns it to the DocCount field.
func (o *MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInner) SetDocCount(v int32) {
	o.DocCount = &v
}

// GetCounter returns the Counter field value if set, zero value otherwise.
func (o *MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInner) GetCounter() MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInnerCounter {
	if o == nil || IsNil(o.Counter) {
		var ret MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInnerCounter
		return ret
	}
	return *o.Counter
}

// GetCounterOk returns a tuple with the Counter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInner) GetCounterOk() (*MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInnerCounter, bool) {
	if o == nil || IsNil(o.Counter) {
		return nil, false
	}
	return o.Counter, true
}

// HasCounter returns a boolean if a field has been set.
func (o *MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInner) HasCounter() bool {
	if o != nil && !IsNil(o.Counter) {
		return true
	}

	return false
}

// SetCounter gets a reference to the given MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInnerCounter and assigns it to the Counter field.
func (o *MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInner) SetCounter(v MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInnerCounter) {
	o.Counter = &v
}

// GetGauge returns the Gauge field value if set, zero value otherwise.
func (o *MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInner) GetGauge() MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInnerGauge {
	if o == nil || IsNil(o.Gauge) {
		var ret MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInnerGauge
		return ret
	}
	return *o.Gauge
}

// GetGaugeOk returns a tuple with the Gauge field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInner) GetGaugeOk() (*MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInnerGauge, bool) {
	if o == nil || IsNil(o.Gauge) {
		return nil, false
	}
	return o.Gauge, true
}

// HasGauge returns a boolean if a field has been set.
func (o *MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInner) HasGauge() bool {
	if o != nil && !IsNil(o.Gauge) {
		return true
	}

	return false
}

// SetGauge gets a reference to the given MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInnerGauge and assigns it to the Gauge field.
func (o *MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInner) SetGauge(v MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInnerGauge) {
	o.Gauge = &v
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInner) GetKey() int64 {
	if o == nil || IsNil(o.Key) {
		var ret int64
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInner) GetKeyOk() (*int64, bool) {
	if o == nil || IsNil(o.Key) {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInner) HasKey() bool {
	if o != nil && !IsNil(o.Key) {
		return true
	}

	return false
}

// SetKey gets a reference to the given int64 and assigns it to the Key field.
func (o *MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInner) SetKey(v int64) {
	o.Key = &v
}

// GetKeyAsString returns the KeyAsString field value if set, zero value otherwise.
func (o *MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInner) GetKeyAsString() string {
	if o == nil || IsNil(o.KeyAsString) {
		var ret string
		return ret
	}
	return *o.KeyAsString
}

// GetKeyAsStringOk returns a tuple with the KeyAsString field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInner) GetKeyAsStringOk() (*string, bool) {
	if o == nil || IsNil(o.KeyAsString) {
		return nil, false
	}
	return o.KeyAsString, true
}

// HasKeyAsString returns a boolean if a field has been set.
func (o *MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInner) HasKeyAsString() bool {
	if o != nil && !IsNil(o.KeyAsString) {
		return true
	}

	return false
}

// SetKeyAsString gets a reference to the given string and assigns it to the KeyAsString field.
func (o *MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInner) SetKeyAsString(v string) {
	o.KeyAsString = &v
}

func (o MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DocCount) {
		toSerialize["doc_count"] = o.DocCount
	}
	if !IsNil(o.Counter) {
		toSerialize["counter"] = o.Counter
	}
	if !IsNil(o.Gauge) {
		toSerialize["gauge"] = o.Gauge
	}
	if !IsNil(o.Key) {
		toSerialize["key"] = o.Key
	}
	if !IsNil(o.KeyAsString) {
		toSerialize["key_as_string"] = o.KeyAsString
	}
	return toSerialize, nil
}

type NullableMetricResourceAggregationResourcesBucketsInnerHistogramBucketsInner struct {
	value *MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInner
	isSet bool
}

func (v NullableMetricResourceAggregationResourcesBucketsInnerHistogramBucketsInner) Get() *MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInner {
	return v.value
}

func (v *NullableMetricResourceAggregationResourcesBucketsInnerHistogramBucketsInner) Set(val *MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableMetricResourceAggregationResourcesBucketsInnerHistogramBucketsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableMetricResourceAggregationResourcesBucketsInnerHistogramBucketsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMetricResourceAggregationResourcesBucketsInnerHistogramBucketsInner(val *MetricResourceAggregationResourcesBucketsInnerHistogramBucketsInner) *NullableMetricResourceAggregationResourcesBucketsInnerHistogramBucketsInner {
	return &NullableMetricResourceAggregationResourcesBucketsInnerHistogramBucketsInner{value: val, isSet: true}
}

func (v NullableMetricResourceAggregationResourcesBucketsInnerHistogramBucketsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMetricResourceAggregationResourcesBucketsInnerHistogramBucketsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


