/*
Chaos

Central Management API - publicly exposed set of APIs for cloud resources

API version: 1.0.0
Contact: help@qernal.support
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_chaos_client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SecretMetaCertificatePayload type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SecretMetaCertificatePayload{}

// SecretMetaCertificatePayload Secret metadata certificate payload
type SecretMetaCertificatePayload struct {
	// Public SSL certificate
	Certificate string `json:"certificate"`
}

type _SecretMetaCertificatePayload SecretMetaCertificatePayload

// NewSecretMetaCertificatePayload instantiates a new SecretMetaCertificatePayload object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSecretMetaCertificatePayload(certificate string) *SecretMetaCertificatePayload {
	this := SecretMetaCertificatePayload{}
	this.Certificate = certificate
	return &this
}

// NewSecretMetaCertificatePayloadWithDefaults instantiates a new SecretMetaCertificatePayload object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSecretMetaCertificatePayloadWithDefaults() *SecretMetaCertificatePayload {
	this := SecretMetaCertificatePayload{}
	return &this
}

// GetCertificate returns the Certificate field value
func (o *SecretMetaCertificatePayload) GetCertificate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Certificate
}

// GetCertificateOk returns a tuple with the Certificate field value
// and a boolean to check if the value has been set.
func (o *SecretMetaCertificatePayload) GetCertificateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Certificate, true
}

// SetCertificate sets field value
func (o *SecretMetaCertificatePayload) SetCertificate(v string) {
	o.Certificate = v
}

func (o SecretMetaCertificatePayload) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SecretMetaCertificatePayload) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["certificate"] = o.Certificate
	return toSerialize, nil
}

func (o *SecretMetaCertificatePayload) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"certificate",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSecretMetaCertificatePayload := _SecretMetaCertificatePayload{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSecretMetaCertificatePayload)

	if err != nil {
		return err
	}

	*o = SecretMetaCertificatePayload(varSecretMetaCertificatePayload)

	return err
}

type NullableSecretMetaCertificatePayload struct {
	value *SecretMetaCertificatePayload
	isSet bool
}

func (v NullableSecretMetaCertificatePayload) Get() *SecretMetaCertificatePayload {
	return v.value
}

func (v *NullableSecretMetaCertificatePayload) Set(val *SecretMetaCertificatePayload) {
	v.value = val
	v.isSet = true
}

func (v NullableSecretMetaCertificatePayload) IsSet() bool {
	return v.isSet
}

func (v *NullableSecretMetaCertificatePayload) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSecretMetaCertificatePayload(val *SecretMetaCertificatePayload) *NullableSecretMetaCertificatePayload {
	return &NullableSecretMetaCertificatePayload{value: val, isSet: true}
}

func (v NullableSecretMetaCertificatePayload) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSecretMetaCertificatePayload) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


