/*
Chaos

Central Management API - publicly exposed set of APIs for cloud resources

API version: 1.0.0
Contact: help@qernal.support
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi_chaos_client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AuthTokenBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AuthTokenBody{}

// AuthTokenBody API auth token create
type AuthTokenBody struct {
	// Name of token
	Name string `json:"name" validate:"regexp=^[A-z-]+$"`
	// Token expiration duration in days. 0 - token will never expire
	ExpiryDuration int32 `json:"expiry_duration"`
}

type _AuthTokenBody AuthTokenBody

// NewAuthTokenBody instantiates a new AuthTokenBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAuthTokenBody(name string, expiryDuration int32) *AuthTokenBody {
	this := AuthTokenBody{}
	this.Name = name
	this.ExpiryDuration = expiryDuration
	return &this
}

// NewAuthTokenBodyWithDefaults instantiates a new AuthTokenBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAuthTokenBodyWithDefaults() *AuthTokenBody {
	this := AuthTokenBody{}
	return &this
}

// GetName returns the Name field value
func (o *AuthTokenBody) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AuthTokenBody) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AuthTokenBody) SetName(v string) {
	o.Name = v
}

// GetExpiryDuration returns the ExpiryDuration field value
func (o *AuthTokenBody) GetExpiryDuration() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.ExpiryDuration
}

// GetExpiryDurationOk returns a tuple with the ExpiryDuration field value
// and a boolean to check if the value has been set.
func (o *AuthTokenBody) GetExpiryDurationOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiryDuration, true
}

// SetExpiryDuration sets field value
func (o *AuthTokenBody) SetExpiryDuration(v int32) {
	o.ExpiryDuration = v
}

func (o AuthTokenBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AuthTokenBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	toSerialize["expiry_duration"] = o.ExpiryDuration
	return toSerialize, nil
}

func (o *AuthTokenBody) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"expiry_duration",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAuthTokenBody := _AuthTokenBody{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAuthTokenBody)

	if err != nil {
		return err
	}

	*o = AuthTokenBody(varAuthTokenBody)

	return err
}

type NullableAuthTokenBody struct {
	value *AuthTokenBody
	isSet bool
}

func (v NullableAuthTokenBody) Get() *AuthTokenBody {
	return v.value
}

func (v *NullableAuthTokenBody) Set(val *AuthTokenBody) {
	v.value = val
	v.isSet = true
}

func (v NullableAuthTokenBody) IsSet() bool {
	return v.isSet
}

func (v *NullableAuthTokenBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAuthTokenBody(val *AuthTokenBody) *NullableAuthTokenBody {
	return &NullableAuthTokenBody{value: val, isSet: true}
}

func (v NullableAuthTokenBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAuthTokenBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


